#!/usr/bin/env bash
# หลัง restore database จาก dump: ยกตัวนับเลขที่ใบรับซื้อ (doc_sequence) ให้ไม่ต่ำกว่าเลขที่มี PDF อยู่แล้วใน Media
# dump คืนล่าสุดไม่มีบิลที่ออกหลังจากนั้น แต่ PDF ของบิลเหล่านั้นยังอยู่ใน Media — ไม่ยกตัวนับ = บิลถัดไปได้เลขซ้ำ
#
#   rclone lsf -R --files-only "media:$S3_BUCKET" | bash services/backup/restore-doc-counters.sh > raise-counters.sql
#   psql -X -v ON_ERROR_STOP=1 -f raise-counters.sql "<database ที่ restore แล้ว>"
#
# อ่านรายชื่อ key ทาง stdin อย่างเดียว (ไม่แตะ Media) · พิมพ์ SQL ทาง stdout · ขั้นตอนเต็ม: .railway/README.md "กู้จริง"
# key: receipts/<สาขา>/<yyyy>/<mm>/<doc_no>.pdf · …/<doc_no>_void.pdf · idcards/<สาขา>/<yyyy>/<mm>/<doc_no>.pdf
#      (apps/api/src/lib/pdfArchive.ts) · doc_no = [<อักษรนำสาขา>-]RC<ปี พ.ศ. 2 หลัก><เดือน>-<ลำดับ ≥ 4 หลัก>
# SQL ที่ได้: ยกตัวนับอย่างเดียว (GREATEST — ไม่ลดเลข) รันซ้ำได้ · รหัสสาขาใน Media ที่ไม่มีใน database = หยุด
# fail-closed: key ใต้ receipts/ หรือ idcards/ ที่อ่านไม่ออก หรือไม่มี key เอกสารเลย = exit ≠ 0 ไม่พิมพ์ SQL
set -euo pipefail

# ตัวนับของใบรับซื้อใช้ prefix นี้เสมอ (apps/api/src/services/buy.ts: next_doc_no(…, 'RC', …))
readonly COUNTER_PREFIX=RC

awk -v counter_prefix="$COUNTER_PREFIX" '
  BEGIN { q = sprintf("%c", 39) } # SQL string quote — the program itself sits inside shell single quotes
  function segment(s) { return s ~ /^[A-Za-z0-9][A-Za-z0-9-]*$/ }
  function digits(s, n) { return length(s) == n && s ~ /^[0-9][0-9]*$/ }
  function reject(key, why) { bad[++nbad] = key " (" why ")" }
  {
    sub(/\r$/, "")
    key = $0
    if (key !~ /^(receipts|idcards)\//) next
    n = split(key, part, "/")
    if (n != 5) { reject(key, "expected <kind>/<branch>/<yyyy>/<mm>/<doc_no>.pdf"); next }
    kind = part[1]; code = part[2]; year = part[3]; month = part[4]; file = part[5]
    if (!segment(code)) { reject(key, "branch code"); next }
    if (!digits(year, 4) || !digits(month, 2)) { reject(key, "year/month folder"); next }
    if (length(file) <= 4 || substr(file, length(file) - 3) != ".pdf") { reject(key, "not a .pdf"); next }
    doc = substr(file, 1, length(file) - 4)
    if (kind == "receipts" && length(doc) > 5 && substr(doc, length(doc) - 4) == "_void") doc = substr(doc, 1, length(doc) - 5)
    if (!segment(doc)) { reject(key, "doc_no"); next }
    at = match(doc, counter_prefix "[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9][0-9][0-9]*$")
    if (!at || (at > 1 && substr(doc, at - 1, 1) != "-")) { reject(key, "doc_no is not [PREFIX-]" counter_prefix "yymm-nnnn"); next }
    period = substr(doc, at + length(counter_prefix), 4)
    running = substr(doc, at + length(counter_prefix) + 5) + 0
    # โฟลเดอร์ปี/เดือนมาจากวันที่บิลเดียวกับงวดของเลข — ต้องตรงกัน (ปี พ.ศ. 2 หลัก = (ค.ศ. + 543) % 100)
    if (substr(period, 3, 2) != month || substr(period, 1, 2) + 0 != (year + 543) % 100) {
      reject(key, "period " period " does not match folder " year "/" month); next
    }
    if (month + 0 < 1 || month + 0 > 12 || running < 1) { reject(key, "month/running number"); next }
    files++
    id = code SUBSEP doc
    if (id in seen) next
    seen[id] = 1
    ndocs++
    row[ndocs] = "  (" q code q ", " q doc q ", " q period q ", " running ")"
  }
  END {
    if (nbad > 0) {
      printf "restore-doc-counters: %d archive key(s) could not be read — fix the listing or this script first:\n", nbad > "/dev/stderr"
      for (i = 1; i <= nbad; i++) print "  " bad[i] > "/dev/stderr"
      exit 2
    }
    if (ndocs == 0) {
      print "restore-doc-counters: no receipts/ or idcards/ PDF keys in the listing — wrong bucket or path?" > "/dev/stderr"
      exit 1
    }
    print "-- generated by services/backup/restore-doc-counters.sh from a Media listing"
    printf "-- %d archive PDF key(s) · %d document number(s)\n", files, ndocs
    print "-- run on the RESTORED database before it takes bills: psql -X -v ON_ERROR_STOP=1 -f <this file> <url>"
    print "-- only ever raises doc_sequence.last_no (GREATEST) · safe to run again"
    print "BEGIN;"
    print ""
    print "CREATE TEMP TABLE media_doc ("
    print "  branch_code text NOT NULL,"
    print "  doc_no text NOT NULL,"
    print "  period text NOT NULL,"
    print "  running integer NOT NULL,"
    print "  PRIMARY KEY (branch_code, doc_no)"
    print ") ON COMMIT DROP;"
    print ""
    print "INSERT INTO media_doc (branch_code, doc_no, period, running) VALUES"
    for (i = 1; i <= ndocs; i++) print row[i] (i < ndocs ? "," : ";")
    print ""
    print "-- every branch code in Media must exist here (a changed/removed code must be mapped by hand)"
    print "DO $check$"
    print "DECLARE missing text;"
    print "BEGIN"
    print "  SELECT string_agg(DISTINCT m.branch_code, " q ", " q ") INTO missing"
    print "  FROM media_doc m LEFT JOIN branch b ON b.code = m.branch_code WHERE b.id IS NULL;"
    print "  IF missing IS NOT NULL THEN"
    print "    RAISE EXCEPTION " q "branch code(s) in Media but not in table branch: %" q ", missing;"
    print "  END IF;"
    print "END"
    print "$check$;"
    print ""
    print "-- raise counters, never lower them; creates counters for periods that started after the dump"
    print "INSERT INTO doc_sequence AS s (branch_id, prefix, period, last_no)"
    print "SELECT b.id, " q counter_prefix q ", m.period, max(m.running)"
    print "FROM media_doc m JOIN branch b ON b.code = m.branch_code"
    print "GROUP BY b.id, m.period"
    print "ON CONFLICT (branch_id, prefix, period) DO UPDATE SET last_no = GREATEST(s.last_no, EXCLUDED.last_no);"
    print ""
    print "DO $verify$"
    print "BEGIN"
    print "  IF EXISTS ("
    print "    SELECT 1 FROM media_doc m"
    print "    JOIN branch b ON b.code = m.branch_code"
    print "    LEFT JOIN doc_sequence s ON s.branch_id = b.id AND s.prefix = " q counter_prefix q " AND s.period = m.period"
    print "    WHERE s.last_no IS NULL OR s.last_no < m.running"
    print "  ) THEN"
    print "    RAISE EXCEPTION " q "a doc_sequence counter is still below a number that has a PDF in Media" q ";"
    print "  END IF;"
    print "END"
    print "$verify$;"
    print ""
    print "-- check: counter >= highest number with a PDF, per branch and period"
    print "SELECT m.branch_code AS branch, m.period, max(m.running) AS media_max, s.last_no AS counter"
    print "FROM media_doc m"
    print "JOIN branch b ON b.code = m.branch_code"
    print "JOIN doc_sequence s ON s.branch_id = b.id AND s.prefix = " q counter_prefix q " AND s.period = m.period"
    print "GROUP BY m.branch_code, m.period, s.last_no"
    print "ORDER BY 1, 2;"
    print ""
    print "-- bills with a PDF in Media but no row in this database = issued after the dump was taken"
    print "-- hand this list to accounting; do not re-enter or renumber them without their decision"
    print "SELECT m.branch_code AS branch, m.doc_no AS missing_from_database"
    print "FROM media_doc m"
    print "JOIN branch b ON b.code = m.branch_code"
    print "LEFT JOIN buy_receipt r ON r.branch_id = b.id AND r.doc_no = m.doc_no"
    print "WHERE r.id IS NULL"
    print "ORDER BY 1, 2;"
    print ""
    print "COMMIT;"
  }
'
